alphagov/gds-boxen

- modules/people/files/alexmuller/govuk-pre-commit-hooks
- modules/people/manifests/alexmuller.pp
Install a pre-commit hook in all of my GOV.UK projects that checks for the string "PRIVATE KEY".
Feel free to use this if you would like to.
> [alexmuller] Add pre-commit hooks for all projects

- modules/teams/manifests/performance-platform.pp
So new users dont have to add this to their personal manifest - adding
the team manifest should give you everything you need to get started.
The downside of this is users who have included this in their personal
manifests will have the definitions repeated twice - however this will
not affect functionality
> Add performance platform ssh config to the team

- README.md
- I've been going through the instructions word for word, and hit this
problem with "please make sure you have the correct access rights"
when cloning the boxen repo as instructed further down in the
README.
> Document a prerequisite: generating an SSH key and adding it to GitHub

- README.md
Mavericks / xcode 6 does not support installing the command line tools
through preferences -> downloads. If we were using boxen-web, this would
be fixed by
https://github.com/boxen/boxen-web/commit/b26abd0d681129eba0b5f46ed43110d873d8fdc2
However, simply running gcc didnt seem to work - running `xcode-select
--install` always seems to work and install the command line tools
> Update instructions on installing xcode

- modules/gds_ssh_config/files/gds_ssh_config
So that we can SSH to these machines like we do with the existing GOV.UK machines.
> Add draft stack to GDS SSH config

- modules/people/manifests/annashipman.pp
- modules/people/manifests/bradleywright.pp
- modules/people/manifests/bruntonspall.pp
- modules/people/manifests/jabley.pp
- modules/people/manifests/jennyd.pp
- modules/projects/manifests/redirector.pp
- modules/projects/manifests/transition-config.pp
- modules/teams/manifests/transition.pp
- In poking around team manifests, I found `projects::redirector`. Redirector is dead. Its purpose (and its name) was changed to transition-config, to reflect that it is now just a repository holding config for the Transition Tool.
- In changing the name of that project manifest file, I've also needed to change the name of the `include projects::redirector` to `include projects::transition-config` in people's manifests that contained that line so that next time they run Boxen, it completes successfully. If any of @bruntonspall, @bradleywright, @annashipman, @jabley or @jennyd object, speak now. :scream:
> Change `projects::redirector` to `projects::transition-config` to reflect the current world

- modules/ssh_config/manifests/init.pp
Fixes this warning:
Warning: Scope(Class[Concat::Setup]): concat::setup is deprecated
as a public API of the concat module and should no longer be
directly included in the manifest.
> Remove deprecated `concat::setup`

- modules/gds_ssh_config/files/gds_ssh_config
Agent forwarding is undesirable because it exposes the use of your private
keys to other people that have root access to the remote machines. It's not
required when using `ProxyCommand` for a jumpbox like this.
> Remove agent forwarding from ci-new SSH config

- modules/gds_printers/manifests/init.pp
Add the 3rd floor printer to `gds_printers` so we don't have to walk to the 6th floor.
> Add 3rd floor printer

- modules/gds_ssh_config/files/gds_ssh_config
- modules/teams/manifests/infrastructure.pp
These jumpbox hostnames were originally added before we decided to use `publishing.service.gov.uk`.
> Update draft environment SSH config

- modules/gds_ssh_config/files/gds_ssh_config
We want everything we do to be consistent, and that includes what
we call machines.
We've settled on `draft-environment`
> Switch `environment-draft` to `draft-environment`

- modules/people/manifests/jabley.pp
Doing this at a global level, rather than scoping on a per-host basis in
`$HOME/ssh/config` since we don’t do that currently.
> [jabley] configure `$HOME/.fabricrc`

- modules/gds_virtualbox/manifests/init.pp
- modules/gds_virtualbox/manifests/recommended.pp
note that it will not auto-upgrade as the pkgdmg provider does not support versioning.
You'll need to remove /var/db/.puppet_pkgdmg_installed_VirtualBox to force an upgrade
> Make version of gds_virtualbox configurable

- modules/gds_ssh_config/files/gds_ssh_config
The draft stack, which existed in a separate vCloud organisation to our
main stack, is now deprecated and has been turned off.
> Removes references to the draft stack

- modules/gds_ssh_config/files/gds_ssh_config
This is the minimum change required to make the staging SSH config work.
#180 changes the hostname used to connect to machines to make it much longer, which is something I don't know if we want to do.
> Switch staging to use new domain

- modules/gds_vpn_profiles/files/profile/gds_dr_github.xml
- modules/gds_vpn_profiles/files/profile/gds_dr_route.xml
These aren’t enabled all the time, but when you need them, it’s good to
have them set up.
> Add disaster recovery VPN configuration

- modules/gds_printers/manifests/init.pp
Using the preferred printer driver should give better printer output,
and allow printer-specific options to be used when configuring.
This change gives more control to the end user.
Note: the driver may need to be installed via munki, in which case we
should not merge this. Not everyone currently has a managed machine.
> Use specific printer driver

- modules/gds_ssh_config/files/gds_ssh_config
People will need to update their SSH config for Carrenza migration, add example here as this is where the [opsmanual](https://github.gds/pages/gds/opsmanual/2nd-line/technical-setup.html?highlight=ssh%20config) points to.
> Add example for new Carrenza Staging SSH config.

- modules/gds_ssh_config/files/gds_ssh_config
- Changes Carrenza sections to just "staging" and "production" (it's all
Carrenza)
- Adds a shortcut so that `host-n.vdc.production` will SSH into new production
> Rationalise SSH configuration

- modules/gds_ssh_config/files/gds_ssh_config
Our CI environment has recently moved to `ci.dev.publishing.service.gov.uk`.
Our deployment scripts for ci-puppet need to be able to ssh to this hostname,
but the ssh config here for our Production environment tries to send
everything at `*.publishing.service.gov.uk` through the Production jumpbox,
which makes the ci-puppet deployment fail.
Adding this bit of config above the wildcard Production section resolves this
issue, allowing our deployment script for ci-puppet to work.
> Add ssh config for new CI hostname

- modules/gds_vpn_profiles/files/profile/gds_mrt.xml
The applications for the tablet room booking systems run on this VPN.
I did define it locally, but it gets deleted whenever I run boxen. So
I’m putting it in boxen.
> Add rooms VPN profile

- modules/gds_ssh_config/files/gds_ssh_config
There is a security vulnerability incoming: https://twitter.com/msfriedl/status/687635945642967040
> Add undocumented "UseRoaming no" to ssh_config or use "-oUseRoaming=no" to prevent upcoming #openssh client bug CVE-2016-0777. More later.
> Add `UseRoaming no` to SSH config

- hiera/common.yaml
- modules/gds_ruby/manifests/init.pp
Update the default list of Ruby versions that we install to use the
latest version in each stable branch.
So that we can install these versions, ensure that the `ruby-build` repo
is tracking the tip of the master branch by setting
`ruby::build::ensure` in `common.yaml`. I think the small risk posed by
us tracking an unreleased check-out of `ruby-build` is outweighed by the
convenience of not having to upgrade this every time we need a more
recent Ruby version.
Uninstall older versions from the stable branches that are no longer
current.
Anyone wishing to continue to use old versions can do so by overriding
this list in Hiera data, as has been done in dff6b154c.
I've removed 2.1.1 from the uninstall list on the assumption that it
has been in the codebase long enough for it to have been …
> Add recent default Ruby versions

- README.md
Could not run the script on my laptop with El Capitan installed. We found out that El Capitan's /bin folder can be found at:
`/usr/local/bin`
Updating the script to save some time to the next person that will try to install GDS boxen on El Capitan.
> Update script to work on El Capitan

- README.md
When installing a new laptop it wasn't immediately obvious what Boxen was or if we needed it to start development in the VM.
> Describe what Boxen is and what it gives us

- Puppetfile
- Puppetfile.lock
- modules/people/manifests/rjw1.pp
The `boxelly/puppet-perl` repo has been removed (the entire boxelly account actually) so this is preventing new starters from running boxen.
Sorry @rjw1! Do you know an alternative?
> Remove perl

- modules/gds_ruby/manifests/init.pp
1.5.* is super old - the last 1.5 version was 1.5.3 in February 2014.
This bumps the default version to be the latest.
> bump default bundler for rubies

- modules/repo/manifests/gds.pp
This commit updates the GHE domain name from `github.gds` to `github.digital.cabinet-office.gov.uk`.
Trello: https://trello.com/c/aTAoiXAm/281-github-enterprise-new-domain-name
> Update GHE domain name

- modules/people/manifests/heathd.pp
- modules/people/manifests/jennyd.pp
- modules/projects/manifests/govuk_content_api.pp
The [`content_api`](https://github.com/alphagov/govuk_content_api) has
been retired, and all content has been migrated to the
[`content_store`](https://github.com/alphagov/content-store).
Therefore, we can remove all references to the Content API, and rely
solely on the Content Store.
https://trello.com/c/TsUsUwD7/153-remove-documentation-on-content-api
> Remove the Content API
